initial development & unit tests
companieshouse/insolvency-api pull request #138
Opened 2023-01-20 15:01 UTC by CHssmith2

2023-01-23 15:22 UTC, adeharrison-ch commented on service/insolvency_service.go
> +		}
could these be condensed in to -
if insolvencyResource.Data.ProgressReport.FromDate == "" || insolvencyResource.Data.ProgressReport.ToDate == "" {

2023-01-24 09:30 UTC, pparlett approved these changes
Code is not incorrect, my approach would have been to use two completely separate checks, one on FromDate and the other on ToDate (i.e. two if statements).

Also, I note the code smell reported by SonarQube on this function. I am not sure why it was not cleared by the recent refactoring?

2023-01-24 10:19 UTC, gshivach requested changes

2023-01-25 14:13 UTC, gshivach approved these changes

2023-01-25 16:53 UTC, merged